# site settings
title: Central Roleplay Community Official Whitelisted
subtitle: 
email: 
description: The Central Roleplay Community Official Whitelisted server is a subsidiary group underneath the parent group Central Roleplay Community. We utilize the Roblox experience "Maple County" to host roleplay sessions, and we are the only officially endorsed private server that receives exclusive access to content other private servers do not yet have permission to use. We offer the most realistic roleplay experience within Maple County, providing comprehensive department training to build your résumé with, and training models that have been taken from the real world! If you want a hyper-realistic roleplay experience on Roblox, the Central Roleplay Community Official Whitelisted server is the place you want to be!
baseurl: "" # the subpath of your site, e.g. /blog
url: https://crpwl.com
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- README.md 
