# site settings
title: CRPC Official Whitelisted
subtitle: 
email: 
description: The Central Roleplay Community Official Whitelisted is a private server based subsidiary within Roblox Maple County.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://crpwl.com
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Team names, titles and social links
people:
- name: fraudwrd
  pic: null
  position: Lead Director
  # social:

- name: CrxzyCookiie
  pic: null
  position: Assistant Director
 # social:

- name: In4antry
  pic: null
  position: Assistant Director
 # social:



# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- README.md 
