# site settings
title: CRPC Official Whitelisted
subtitle: 
email: 
description: The Central Roleplay Community Official Whitelisted is a private server based subsidiary within Roblox Maple County.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://crpwl.com
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Team names, titles and social links
people:
- name: Kay Garland
  pic: FMPD1.png
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: FMPD2.png
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: FMPD3.png
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- README.md 
